import assert from "node:assert/strict";
import fs from "node:fs";

const html = fs.readFileSync("frontend/index.html", "utf8");
const app = fs.readFileSync("frontend/app.js", "utf8");
const api = fs.readFileSync("frontend/api.js", "utf8");
const styles = fs.readFileSync("frontend/styles.css", "utf8");

for (const page of ["Dashboard", "Network", "Systems", "Active Directory", "Tickets", "Automation", "Architecture"]) {
  assert.match(html, new RegExp(`>${page}<`), `${page} navigation is missing`);
}

assert.match(app, /Planned Phase/);
assert.match(app, /state\.devices\.map/);
assert.match(app, /state\.devices = overview\.devices/);
assert.doesNotMatch(app, /api\.devices\(\)/);
assert.match(app, /deviceCard/);
assert.match(app, /renderDrawer/);
assert.match(app, /Printer resources/);
assert.doesNotMatch(app, /Active printer incidents/);
assert.match(app, /openImpactedDevices/);
assert.match(app, /overview\?\.impacted_device_alerts/);
assert.match(app, /openPrinterAlerts/);
assert.match(app, /function openServiceAlerts/);
assert.match(app, /"service-alerts"/);
assert.match(app, /data-return-list/);
assert.match(app, /data-drawer-back/);
assert.match(app, /recent_events/);
assert.match(app, /device\.department/);
assert.match(app, /device\.floor/);
assert.match(app, /events\.slice\(0, 15\)/);
assert.match(app, /Active Directory account health/);
assert.match(app, /data-dashboard-action="account-alerts"/);
assert.match(app, /function openAccountAlerts/);
assert.match(app, /data-dashboard-ad-user/);
assert.match(app, /accountHealth\.locked_accounts/);
assert.match(app, /accountHealth\.password_expired_accounts/);
assert.match(app, /accountHealth\.disabled_accounts/);
assert.match(app, /state\.page === "dashboard" \? api\.directoryAccountHealth\(\)/);
assert.match(api, /\/api\/directory\/account-health/);
assert.match(styles, /\.account-health-summary\.attention/);
assert.match(styles, /\.account-health-summary\.healthy/);
assert.match(styles, /\.recent-event-list\s*\{[^}]*overflow-y:\s*auto;/);
assert.match(app, /data-infrastructure-action/);
assert.match(app, /Printing unavailable/);
assert.match(app, /Backend unavailable/);
assert.match(app, /pingSource: "WS01"/);
assert.match(app, /state\.pingSource = event\.target\.value/);
assert.match(app, /preserveInteractivePage/);
assert.match(app, /state\.diagnosticsActive/);
assert.match(app, /\.diagnostic-panel/);
assert.match(app, /function diagnosticTranscript/);
assert.match(app, /COMMAND OUTPUT/);
assert.match(styles, /\.terminal-result/);
assert.match(api, /\/api\/lab/);
assert.match(api, /\/api\/devices/);
assert.match(api, /\/api\/connectivity\/ping/);
assert.match(api, /\/api\/connectivity\/diagnostic/);
assert.match(api, /network-info/);
assert.match(app, /Traceroute/);
assert.match(app, /DNS lookup/);
assert.match(app, /Service health/);
assert.match(app, /function renderActiveDirectory/);
assert.match(api, /\/api\/directory/);
assert.match(api, /\/api\/provisioning\/workstations\/draft/);
assert.match(api, /\/api\/provisioning\/workstations\/apply/);
assert.match(app, /data-add-workstation/);
assert.match(app, /data-apply-workstation/);
assert.match(app, /data-add-employee/);
assert.match(app, /data-create-employee/);
assert.match(app, /data-unassign-employee/);
assert.match(app, /data-assign-employee/);
assert.match(app, /Unassigned Members/);
assert.match(app, /Remote Users/);
assert.match(app, /Account Attention/);
assert.match(app, /account-attention-tab/);
assert.match(app, /attentionUsers\.length \? "has-attention" : "is-clear"/);
assert.match(app, /class="attention-icon"/);
assert.match(app, /password_expired/);
assert.match(app, /Password policy/);
assert.match(app, /AD DS · DNS · Kerberos/);
assert.match(app, /Controlled access check/);
assert.match(app, /ACCESS GRANTED/);
assert.match(api, /\/api\/fileserver\/access-check/);
assert.match(app, /Manage Access/);
assert.match(app, /data-file-membership/);
assert.match(app, /File Share Access/);
assert.match(app, /fileUserAccess/);
assert.match(app, /data-return-user/);
assert.match(api, /\/api\/fileserver\/users/);
assert.match(styles, /\.directory-tabbar\s*\{[^}]*display:\s*flex/);
assert.match(styles, /\.account-attention-tab\.has-attention/);
assert.match(styles, /\.account-attention-tab\.is-clear|\.account-attention-tab\s*\{/);
assert.match(app, /fileAccessShare/);
assert.match(app, /Loading live group membership/);
assert.match(app, /Current access/);
assert.match(api, /memberships/);
assert.match(app, /state\.page === "active-directory"/);
assert.match(app, /Unassigned — assign a device later/);
assert.match(app, /data-remove-device/);
assert.match(api, /\/api\/provisioning\/employees/);
assert.match(api, /assignEmployee/);
assert.match(api, /\/api\/provisioning\/devices/);
assert.match(app, /Laptop \(LTP\)/);
assert.match(app, /device\.form_factor !== "laptop"/);
assert.match(app, /device\.form_factor === "laptop"/);
assert.match(app, /5 visible before scrolling/);
assert.match(app, /3 visible before scrolling/);
assert.match(app, /2 visible before scrolling/);
assert.match(app, /8 visible before scrolling/);
assert.match(styles, /\.system-table-scroll\.workstation-list\s*\{[^}]*max-height:/);
assert.match(styles, /\.system-table-scroll\.laptop-list\s*\{[^}]*max-height:/);
assert.match(styles, /\.system-table-scroll\.printer-list\s*\{[^}]*max-height:/);
assert.match(styles, /\.directory-table-scroll\s*\{[^}]*overscroll-behavior:\s*contain/);
assert.match(app, /provisionDeviceType/);
assert.match(app, /Temporary password/);
assert.match(app, /data-ad-action/);
assert.match(app, /data-ad-membership/);
assert.match(app, /function openDirectoryGroup/);
assert.match(app, /data-directory-group/);
assert.match(app, /data-directory-view/);
assert.match(app, /directory-tabs/);
assert.match(app, /directory-summary/);
assert.doesNotMatch(app, /tree-folder|▣|□/);
assert.match(app, /Computers/);
assert.match(app, /Disabled Accounts/);
assert.match(app, /Assigned workstation/);
assert.doesNotMatch(app, /http:\/\/127\.0\.0\.1:808[0-3]\/status/);
assert.doesNotMatch(app, /directPrinterPages/);
assert.match(app, /device\.host_port/);
assert.match(styles, /\.backend-banner\[hidden\]\s*\{\s*display:\s*none;/);

console.log("Frontend structure checks passed.");
