[global]
  server role = standalone server
  workgroup = NETOPSLAB
  server string = NetOps Lab FILE01
  map to guest = Bad User
  log file = /var/log/samba/log.%m
  max log size = 100
  disable netbios = yes
  smb ports = 445

[Public]
  path = /srv/shares/Public
  browseable = yes
  read only = no
  guest ok = yes

[HR]
  path = /srv/shares/HR
  browseable = yes
  read only = no
  guest ok = no

[Finance]
  path = /srv/shares/Finance
  browseable = yes
  read only = no
  guest ok = no

[Engineering]
  path = /srv/shares/Engineering
  browseable = yes
  read only = no
  guest ok = no

[IT-Tools]
  path = /srv/shares/IT-Tools
  browseable = yes
  read only = no
  guest ok = no
